## Data collection using selenium

In [2]:
pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Collecting selenium
  Using cached selenium-4.12.0-py3-none-any.whl (9.4 MB)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.14)
Collecting trio-websocket~=0.9
  Using cached trio_websocket-0.10.3-py3-none-any.whl (17 kB)
Collecting trio~=0.17
  Using cached trio-0.22.2-py3-none-any.whl (400 kB)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.12.7)
Collecting outcome
  Using cached outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Collecting exceptiongroup>=1.0.0rc9
  Using cached exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Collecting wsproto>=0.14
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Installing collected packages: outcome, h11, exceptiongroup, wsproto, trio, trio-websocket, selenium
Successfully installed exceptiongroup-1.1.3 h11-0.14.0 outcome-1.2.0 selenium-4.12.0 trio-0.22.2 trio-websocket-0.10.3 wsproto-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd
# import the webdriver library that will help us to create a driver to scrape a specific website
from selenium import webdriver 
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# take the link
web_link="https://www.uttamis.co.tz/fund-performance"

# Create a Chrome WebDriver instance with specified options (e.g., headless mode)
driver = webdriver.Chrome(options=Options())

# Open the web link specified by the 'web_link' variable
driver.get(web_link)

# Maximize the browser window for better visibility and interaction
driver.maximize_window()

# Find and select a specific option element on the webpage using XPath
button = driver.find_element(By.XPATH, '//*[@id="data_table_length"]/label/select/option[4]')

# Click the selected option to perform an action on the webpage
button.click()

In [25]:
# Find all elements matching a specific XPath pattern for the 'name_scheme' column
name_scheme = driver.find_elements(By.XPATH, "//tbody/tr/td[2]")

# Find all elements matching a specific XPath pattern for the 'net_asset_value' column
net_asset_value = driver.find_elements(By.XPATH, "//tbody/tr/td[3]")

# Find all elements matching a specific XPath pattern for the 'outstanding_no_of_units' column
outstanding_no_of_units = driver.find_elements(By.XPATH, "//tbody/tr/td[4]")

# Find all elements matching a specific XPath pattern for the 'nav_per_unit' column
nav_per_unit = driver.find_elements(By.XPATH, "//tbody/tr/td[5]")

# Find all elements matching a specific XPath pattern for the 'sale_price_per_unit' column
sale_price_per_unit = driver.find_elements(By.XPATH, "//tbody/tr/td[6]")

# Find all elements matching a specific XPath pattern for the 'repurchase_price_per_unit' column
repurchase_price_per_unit = driver.find_elements(By.XPATH, "//tbody/tr/td[7]")

# Find all elements matching a specific XPath pattern for the 'date_valued' column
date_valued = driver.find_elements(By.XPATH, "//tbody/tr/td[8]")

In [26]:
# Extracting data from multiple web elements and organizing it into a list of dictionaries.
# Each dictionary represents a row of data with columns such as 'name_scheme,' 'net_asset_value,' 'outstanding_no_of_units,' 'nav_per_unit,' 'sale_price_per_unit,' 'repurchase_price_per_unit,' and 'date_valued.'
# The 'for' loop iterates through elements of corresponding columns, extracts their text content, and creates a dictionary for each row of data.
# Each dictionary is then appended to the 'data' list, resulting in a structured representation of the web table data.

data=[]

for i in range(len(name_scheme)):
    temp={"name_scheme":name_scheme[i].text,
         "net_asset_value":net_asset_value[i].text,
         "outstanding_no_of_units":outstanding_no_of_units[i].text,
         "nav_per_unit":nav_per_unit[i].text,
         "sale_price_per_unit":sale_price_per_unit[i].text,
         "repurchase_price_per_unit":repurchase_price_per_unit[i].text,
         "date_valued":date_valued[i].text}
    data.append(temp)

In [ ]:
# Change web page and re-run the code above and store themm in 3 csv files

In [27]:
# converting it to a dataframe and displaying it
df=pd.DataFrame(data)
df

,name_scheme,net_asset_value,outstanding_no_of_units,nav_per_unit,sale_price_per_unit,repurchase_price_per_unit,date_valued
0,Umoja Fund,"203,669,701,871.9100","426,362,800.9800",477.6911,477.6911,472.9142,26-01-2017
1,Wekeza Maisha Fund,"3,682,688,078.1900","11,662,611.0300",315.7687,315.7687,309.4534,26-01-2017
2,Watoto Fund,"3,305,994,999.8800","11,764,594.5100",281.0122,281.0122,278.2021,26-01-2017
3,Jikimu Fund,"24,833,849,763.8400","203,269,321.5400",122.1721,122.1721,119.7287,26-01-2017
4,Liquid Fund,"9,303,011,179.7800","58,971,882.0000",157.7533,157.7533,157.7533,26-01-2017
...,...,...,...,...,...,...,...
2536,Umoja Fund,"204,639,102,456.9000","469,288,926.9200",436.0621,436.0621,431.7015,02-01-2015
2537,Wekeza Maisha Fund,"3,478,176,337.4600","11,974,460.8400",290.4662,290.4662,284.6569,02-01-2015
2538,Watoto Fund,"2,498,211,121.3600","9,324,862.5200",267.9086,267.9086,265.2295,02-01-2015
2539,Jikimu Fund,"16,214,757,965.5200","121,678,968.1300",131.1036,131.1036,128.4815,02-01-2015
2540,Liquid Fund,"570,785,874.8700","4,716,811.9300",121.0109,121.0109,121.0109,02-01-2015

In [28]:
# Storing first 2541 rows of data
df.to_csv("test1",index=False)

In [ ]:
# Storing second 2541 rows of data
df.to_csv("test2",index=False)

In [ ]:
# Storing third 2541 rows of data
df.to_csv("test3",index=False)

In [ ]:
# Import pandas library
import pandas as pd

In [ ]:
# Read all 3 stored datasets
df1=pd.read_csv('test1')
df2=pd.read_csv('test2')
df3=pd.read_csv('test3')

In [ ]:
# Combine the 3 data sets to 1
comb=pd.concat([df1,df2,df3], axis=0,ignore_index=True)

In [2]:
# Storing the full data set
comb.to_csv('Net Asset Value (NAV) Dataset',index=False)